### ISSUE TITLE
Troubles on Android

### ISSUE THREAD

**Issue by rafaellop** [JcDenton86/cordova-plugin-jc-googledrive#1]
@JcDenton86 First of all, thanks for the plugin. It is superuseful and easy to use. Now issues :-)

It's not mentioned in the README and probably obvious to majority, but I've been stuck for several minutes when my debug package (not signed) doesn't work at all with the plugin. Finally I did a full build and it started to work. Would be great if mentioned in the docs or if there's an option to test in the debug mode.

Bigger issue is the gms dependency conflict with other plugins. Your `plugin.xml` defines the framework as `<framework src="com.google.android.gms:play-services-drive:10.2.0" />` which cause that the `build.gradle` file also contains the explicit version. I think that majority of developers who hate the dependencies mess as I do would be happy to see there the framework definition as `<framework src="com.google.android.gms:play-services-drive:+" />`. In my case this solved a huge crashing issue which has been giving me the following logcat error:

```03-29 23:20:54.204: E/AndroidRuntime(29159): java.lang.NoSuchFieldError: No instance field zzcuA of type Lcom/google/android/gms/internal/zzbxp; in class Lcom/google/android/gms/internal/zzals; or its superclasses (declaration of 'com.google.android.gms.internal.zzals' appears in /data/app/com.creamsoft.mygi-1/base.apk)```

Although the file has been uploaded to the google drive, the app crashed immediately after the above logcat entry. I've changed the gradle dependency for your plugin entry to + as above and everything started to work perfectly smooth and without any errors.

Please consider this change if you think it's reasonable or if I'm wrong please explain why if you had a free time. Thanks for the plugin anyway. It's life saver! :-)

**Comment by JcDenton86** [comment]
@rafaellop glad the plugin helped you and thanks for your suggestions. Will check them on the weekend. 

As for the debug package, did you create a separate oauth client id using its SHA1? Because during the development of the plugin I was using only my debug package and on developer console I have two oauth client ids for Android (one for debug and one for release).

**Comment by rafaellop** [comment]
Yes, I use my own SHA1 for the google drive api login generated with the keytool.
