### ISSUE TITLE
uploadFile pads NULL at very end of uploaded text file with size < 1024

### ISSUE THREAD

**Issue by rongmz** [JcDenton86/cordova-plugin-jc-googledrive#11]
When I use `uploadFile `method to upload a text file from my app's cache directory, pads NULL at very end of the file, making size as multiple of 1024 bytes.

Code I am using:
```
var uploadFile = (cordova.file.cacheDirectory + fileName).replace(/^file:\/\//,'');
console.log(uploadFile);
window.plugins.gdrive.uploadFile(uploadFile, isAppData, function (response) {
     // upload done. 
     console.log(response);
}, function (error){
     // upload error
     console.log(error);
});
```

This code successfully uploads a 12 bytes text data, but it pads NULL at end and makes the file size of 1024. See attached screenshot of the file after i download from google drive manually and opened in a text editor.
![github](https://user-images.githubusercontent.com/9639416/28242050-18c1dcdc-69bf-11e7-9c66-f831d2df48b0.PNG)

**Comment by JcDenton86** [comment]
Hi, I cannot reproduce your issue. I uploaded a .txt file having the same content ('this is a sample'). When downloaded and opened it was fine (without the NULL pads). How do you create the file before uploading?

**Comment by rongmz** [comment]
Hi, the file is being generated from cordova-plugin-file plugin. I got this issue solved by using a fork of this project [Here](https://github.com/Vargash/cordova-plugin-jc-googledrive) 
I have gone through the source code, and noticed the below lines, that are causing NULL issue for me. See below:
`code with issue:`
![image](https://user-images.githubusercontent.com/9639416/28462994-a29986b4-6e3b-11e7-9917-0e67043ea1a9.png)

`solution that worked:`
![image](https://user-images.githubusercontent.com/9639416/28463025-cda810aa-6e3b-11e7-974e-f668c1b2a5b1.png)

**Comment by rongmz** [comment]
Closing this issue I have used this fork https://github.com/Vargash/cordova-plugin-jc-googledrive
