### ISSUE TITLE
Implement full access APIs (beyond app folder)

### ISSUE THREAD

**Issue by joepasq** [JcDenton86/cordova-plugin-jc-googledrive#15]
The `cordova-plugin-jc-googledrive` presently only allows accessing and working with files. I'd like to request folder access as well. The iOS client library [supports working with](https://github.com/google/google-api-objectivec-client-for-rest/blob/master/Examples/DriveSample/DriveSampleWindowController.m#L710) folders.

Update: Sorry for my poor wording. I meant to say for full drive access more just the app's own files and folders.

**Comment by joepasq** [comment]
After [reviewing the Google Drive documentation](https://developers.google.com/drive/android/queries) I don't think this is possible. In the first section of _Querying for Files_ the following note is displayed.

> Note: The Android Drive API only works with the https://www.googleapis.com/auth/drive.file scope. *This means that only files which a user has opened or created with your application can be matched by a query*

**Comment by rodrigosk8s** [comment]
I work with android for the moment, but what I really need to know if this plugin could give access to files that are not loaded by the application.
I am implementing this plugin in an application with ionic v1 and angularjs.

Thank you so much.

**Comment by joepasq** [comment]
Yes, unfortunately that is my understanding for the Android API. [This StackOverflow question asks the same](https://stackoverflow.com/questions/34253889/list-all-files-in-drive) and the answer from [the queries documentation page](https://developers.google.com/drive/android/queries) is

> Note: The Android Drive API only works with the https://www.googleapis.com/auth/drive.file scope. This means that only files which a user has opened or created with your application can be matched by a query.

---

In theory you could use the Drive REST APIs with Android but this project doesn't have an implementation for those. The [Drive REST documentation has a quickstart for Android](https://developers.google.com/drive/v3/web/quickstart/android), excerpt below.

> Note: This quickstart illustrates the use of the Drive REST API in an Android application. However, in the majority of cases production Drive apps will strongly benefit by making use of the Drive API for Android, which is integrated with Google Play Services and offers better performance. Before using the Drive REST API in your Android application, you should carefully review the Drive API for Android and use it in your application if possible. A Drive API for Android Quickstart is available if you want to learn more.

The reason that **REST + Android + Cordova should not work is because the REST APIs require OAuth sign-in which is not supported from within the Cordova web view**. Please see ["Google login with cordova won't work."](https://stackoverflow.com/questions/46159235/google-login-with-cordova-wont-work-error-10-in-android-and-bad-request-in-ios), ["Modernizing OAuth interactions in Native Apps for Better Usability and Security"](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html), and ["Inappbrowser ionic doesn't load Oauth"](https://stackoverflow.com/questions/40379128/inappbrowser-ionic-doesnt-load-oauth).

---

So at the end of the day this plugin works by wrapping the Android native Drive API and the iOS* Drive REST API, and relying on Android native authentication and iOS OAuth authentication. The native restrictions on Android also provide tighter integration with Drive and some extra functions like requesting a synchronization. (I haven't yet started adding functionality to the iOS code so I may be slightly wrong.)
