### ISSUE TITLE
No callback if clicked outside the auth account selection list

### ISSUE THREAD

**Issue by rafaellop** [JcDenton86/cordova-plugin-jc-googledrive#6]
If an app is unauthorized the device shows the account selection dialog with list of google accounts on the device. Something like this (taken from google):

![accounts](http://www.androidhive.info/wp-content/uploads/2014/02/android-google-plus-sign-in-choosing-the-account.png)

If you now click on the gray area outside the list, the list is closed with no auth but no callback is given. I've got spinner there which locks my app and now I must close it after a timeout instead of react to the dismissed auth.

**Comment by JcDenton86** [comment]
Thanks for reporting. I will upload the fix
